WITH base AS
  (SELECT cr.call_id,
          cr.call_date,
          cr.event_at,
          cr.segment_no,
          cr.agent_login,
          cr.exit_skill,
          cr.total_wait_sec,
          cr.talk_sec,
          cr.hold_sec,
          cr.consult_sec,
          cr.caller_number,
          cr.dialed_number,
          cr.global_call_uid,
          cr.crm_payload,
          ROW_NUMBER() OVER (PARTITION BY cr.call_id
                             ORDER BY cr.event_at, cr.segment_no) AS rn
   FROM call_segments cr
   WHERE cr.call_date >= '2026-01-01'
     AND cr.call_date < '2026-09-01'),
     agents AS
  (SELECT b.call_id,
          b.rn,
          b.agent_login,
          CAST(b.exit_skill AS INTEGER) AS exit_skill,
          b.total_wait_sec,
          b.talk_sec,
          b.hold_sec,
          b.consult_sec,
          b.caller_number,
          b.call_date,
          b.event_at,
          b.global_call_uid,
          b.crm_payload,
          ROW_NUMBER() OVER (PARTITION BY b.call_id
                             ORDER BY b.rn) AS agent_rn
   FROM base b
   WHERE b.agent_login IS NOT NULL
     AND b.agent_login <> ''
     AND b.exit_skill IS NOT NULL
     AND b.exit_skill <> 0
     AND b.dialed_number <> '792501'
     AND (b.caller_number NOT LIKE 'T%'
          OR b.caller_number IS NULL)),
     last_skill AS
  (SELECT call_id,
          MAX(agent_rn) AS max_agent_rn,
          MAX(rn) AS max_rn
   FROM agents
   GROUP BY call_id),
     multi_skill AS
  (SELECT call_id,
          max_agent_rn,
          max_rn
   FROM last_skill
   WHERE max_agent_rn >= 2),
     CHAIN AS
  (SELECT a.call_id,
          a.rn,
          a.agent_login,
          a.exit_skill AS skill_display,
          a.total_wait_sec,
          a.talk_sec,
          a.hold_sec,
          a.consult_sec,
          a.caller_number,
          a.call_date,
          a.event_at,
          a.global_call_uid,
          a.crm_payload,
          a.agent_rn
   FROM agents a
   INNER JOIN multi_skill m ON a.call_id = m.call_id
   AND a.agent_rn <= m.max_agent_rn), all_with_bridge AS
  (SELECT b.call_id,
          b.rn,
          b.total_wait_sec,
          b.talk_sec,
          CASE
              WHEN a.agent_rn IS NOT NULL THEN 1
              ELSE 0
          END AS is_agent,
          m.max_rn
   FROM base b
   INNER JOIN multi_skill m ON b.call_id = m.call_id
   LEFT JOIN agents a ON b.call_id = a.call_id
   AND b.rn = a.rn
   WHERE b.rn <= m.max_rn),
                                      bridge_time AS
  (SELECT call_id,
          SUM(CASE
                  WHEN is_agent = 0 THEN COALESCE(total_wait_sec, 0) + COALESCE(talk_sec, 0)
                  ELSE 0
              END) AS bridge_total
   FROM all_with_bridge
   GROUP BY call_id),
                                      client_num AS
  (SELECT call_id,
          CASE
              WHEN LENGTH(TRIM(caller_number)) > 10
                   AND (SUBSTR(TRIM(caller_number), 1, 1) = '7'
                        OR SUBSTR(TRIM(caller_number), 1, 1) = '8') THEN SUBSTR(TRIM(caller_number), 2)
              ELSE TRIM(caller_number)
          END AS client_number
   FROM base),
                                      asai_data AS
  (SELECT call_id,
          MAX(crm_payload) AS asai_value
   FROM base
   GROUP BY call_id)
SELECT /* Основная информация */  DATE(MAX(c.call_date)) AS [Дата],
                                  strftime('%Y-%m-%d %H:%M', MAX(c.event_at)) AS [Дата-время],
                                  c.call_id AS [CallID],
                                  MAX(c.global_call_uid) AS [UCID],
                                  MAX(cl.client_number) AS [Номер клиента],
                                  MAX(ad.asai_value) AS [ASAI_UUI], /* Навыки */  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 1 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill1],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 2 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill2],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 3 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill3],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 4 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill4],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 5 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill5],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 6 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill6],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 7 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill7],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 8 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill8],
                                                                                  CAST(MAX(CASE
                                                                                               WHEN c.agent_rn = 9 THEN c.skill_display
                                                                                           END) AS INTEGER) AS [Skill9], /* Skill 1 */  MAX(CASE
                                                                                                                                                WHEN c.agent_rn = 1 THEN c.total_wait_sec
                                                                                                                                                ELSE 0
                                                                                                                                            END) AS [Skill1_Ожидание],
                                                                                                                                        MAX(CASE
                                                                                                                                                WHEN c.agent_rn = 1 THEN c.talk_sec
                                                                                                                                                ELSE 0
                                                                                                                                            END) AS [Skill1_Разговор],
                                                                                                                                        MAX(CASE
                                                                                                                                                WHEN c.agent_rn = 1 THEN c.hold_sec
                                                                                                                                                ELSE 0
                                                                                                                                            END) AS [Skill1_Удержание],
                                                                                                                                        MAX(CASE
                                                                                                                                                WHEN c.agent_rn = 1 THEN c.consult_sec
                                                                                                                                                ELSE 0
                                                                                                                                            END) AS [Skill1_Консультация], /* Skill 2 */  MAX(CASE
                                                                                                                                                                                                  WHEN c.agent_rn = 2 THEN c.total_wait_sec
                                                                                                                                                                                                  ELSE 0
                                                                                                                                                                                              END) AS [Skill2_Ожидание],
                                                                                                                                                                                          MAX(CASE
                                                                                                                                                                                                  WHEN c.agent_rn = 2 THEN c.talk_sec
                                                                                                                                                                                                  ELSE 0
                                                                                                                                                                                              END) AS [Skill2_Разговор],
                                                                                                                                                                                          MAX(CASE
                                                                                                                                                                                                  WHEN c.agent_rn = 2 THEN c.hold_sec
                                                                                                                                                                                                  ELSE 0
                                                                                                                                                                                              END) AS [Skill2_Удержание],
                                                                                                                                                                                          MAX(CASE
                                                                                                                                                                                                  WHEN c.agent_rn = 2 THEN c.consult_sec
                                                                                                                                                                                                  ELSE 0
                                                                                                                                                                                              END) AS [Skill2_Консультация], /* Skill 3 */  MAX(CASE
                                                                                                                                                                                                                                                    WHEN c.agent_rn = 3 THEN c.total_wait_sec
                                                                                                                                                                                                                                                    ELSE 0
                                                                                                                                                                                                                                                END) AS [Skill3_Ожидание],
                                                                                                                                                                                                                                            MAX(CASE
                                                                                                                                                                                                                                                    WHEN c.agent_rn = 3 THEN c.talk_sec
                                                                                                                                                                                                                                                    ELSE 0
                                                                                                                                                                                                                                                END) AS [Skill3_Разговор],
                                                                                                                                                                                                                                            MAX(CASE
                                                                                                                                                                                                                                                    WHEN c.agent_rn = 3 THEN c.hold_sec
                                                                                                                                                                                                                                                    ELSE 0
                                                                                                                                                                                                                                                END) AS [Skill3_Удержание],
                                                                                                                                                                                                                                            MAX(CASE
                                                                                                                                                                                                                                                    WHEN c.agent_rn = 3 THEN c.consult_sec
                                                                                                                                                                                                                                                    ELSE 0
                                                                                                                                                                                                                                                END) AS [Skill3_Консультация], /* Skill 4 */  MAX(CASE
                                                                                                                                                                                                                                                                                                      WHEN c.agent_rn = 4 THEN c.total_wait_sec
                                                                                                                                                                                                                                                                                                      ELSE 0
                                                                                                                                                                                                                                                                                                  END) AS [Skill4_Ожидание],
                                                                                                                                                                                                                                                                                              MAX(CASE
                                                                                                                                                                                                                                                                                                      WHEN c.agent_rn = 4 THEN c.talk_sec
                                                                                                                                                                                                                                                                                                      ELSE 0
                                                                                                                                                                                                                                                                                                  END) AS [Skill4_Разговор],
                                                                                                                                                                                                                                                                                              MAX(CASE
                                                                                                                                                                                                                                                                                                      WHEN c.agent_rn = 4 THEN c.hold_sec
                                                                                                                                                                                                                                                                                                      ELSE 0
                                                                                                                                                                                                                                                                                                  END) AS [Skill4_Удержание],
                                                                                                                                                                                                                                                                                              MAX(CASE
                                                                                                                                                                                                                                                                                                      WHEN c.agent_rn = 4 THEN c.consult_sec
                                                                                                                                                                                                                                                                                                      ELSE 0
                                                                                                                                                                                                                                                                                                  END) AS [Skill4_Консультация], /* Skill 5 */  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                        WHEN c.agent_rn = 5 THEN c.total_wait_sec
                                                                                                                                                                                                                                                                                                                                                        ELSE 0
                                                                                                                                                                                                                                                                                                                                                    END) AS [Skill5_Ожидание],
                                                                                                                                                                                                                                                                                                                                                MAX(CASE
                                                                                                                                                                                                                                                                                                                                                        WHEN c.agent_rn = 5 THEN c.talk_sec
                                                                                                                                                                                                                                                                                                                                                        ELSE 0
                                                                                                                                                                                                                                                                                                                                                    END) AS [Skill5_Разговор],
                                                                                                                                                                                                                                                                                                                                                MAX(CASE
                                                                                                                                                                                                                                                                                                                                                        WHEN c.agent_rn = 5 THEN c.hold_sec
                                                                                                                                                                                                                                                                                                                                                        ELSE 0
                                                                                                                                                                                                                                                                                                                                                    END) AS [Skill5_Удержание],
                                                                                                                                                                                                                                                                                                                                                MAX(CASE
                                                                                                                                                                                                                                                                                                                                                        WHEN c.agent_rn = 5 THEN c.consult_sec
                                                                                                                                                                                                                                                                                                                                                        ELSE 0
                                                                                                                                                                                                                                                                                                                                                    END) AS [Skill5_Консультация], /* Skill 6 */  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                          WHEN c.agent_rn = 6 THEN c.total_wait_sec
                                                                                                                                                                                                                                                                                                                                                                                                          ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                      END) AS [Skill6_Ожидание],
                                                                                                                                                                                                                                                                                                                                                                                                  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                          WHEN c.agent_rn = 6 THEN c.talk_sec
                                                                                                                                                                                                                                                                                                                                                                                                          ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                      END) AS [Skill6_Разговор],
                                                                                                                                                                                                                                                                                                                                                                                                  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                          WHEN c.agent_rn = 6 THEN c.hold_sec
                                                                                                                                                                                                                                                                                                                                                                                                          ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                      END) AS [Skill6_Удержание],
                                                                                                                                                                                                                                                                                                                                                                                                  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                          WHEN c.agent_rn = 6 THEN c.consult_sec
                                                                                                                                                                                                                                                                                                                                                                                                          ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                      END) AS [Skill6_Консультация], /* Skill 7 */  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHEN c.agent_rn = 7 THEN c.total_wait_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                        END) AS [Skill7_Ожидание],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHEN c.agent_rn = 7 THEN c.talk_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                        END) AS [Skill7_Разговор],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHEN c.agent_rn = 7 THEN c.hold_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                        END) AS [Skill7_Удержание],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                            WHEN c.agent_rn = 7 THEN c.consult_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                        END) AS [Skill7_Консультация], /* Skill 8 */  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHEN c.agent_rn = 8 THEN c.total_wait_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END) AS [Skill8_Ожидание],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHEN c.agent_rn = 8 THEN c.talk_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END) AS [Skill8_Разговор],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHEN c.agent_rn = 8 THEN c.hold_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END) AS [Skill8_Удержание],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHEN c.agent_rn = 8 THEN c.consult_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END) AS [Skill8_Консультация], /* Skill 9 */  MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHEN c.agent_rn = 9 THEN c.total_wait_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            END) AS [Skill9_Ожидание],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHEN c.agent_rn = 9 THEN c.talk_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            END) AS [Skill9_Разговор],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHEN c.agent_rn = 9 THEN c.hold_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            END) AS [Skill9_Удержание],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        MAX(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                WHEN c.agent_rn = 9 THEN c.consult_sec
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            END) AS [Skill9_Консультация], /* Мосты */  MAX(bt.bridge_total) AS [Время мостов], /* Количество переводов */  COUNT(*) - 1 AS [Количество переводов], /* Время до финального навыка */  SUM(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHEN c.agent_rn < m.max_agent_rn THEN COALESCE(c.total_wait_sec, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END) AS [Ожидание до финального],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      SUM(CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              WHEN c.agent_rn < m.max_agent_rn THEN COALESCE(c.talk_sec, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ELSE 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          END) AS [Разговор до финального]
FROM CHAIN c
INNER JOIN multi_skill m ON c.call_id = m.call_id
LEFT JOIN client_num cl ON c.call_id = cl.call_id
LEFT JOIN asai_data ad ON c.call_id = ad.call_id
LEFT JOIN bridge_time bt ON c.call_id = bt.call_id
GROUP BY c.call_id
ORDER BY [Дата],
         c.call_id;
